name: Jekyll Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Jekyll
        run: |
          bundle install
          bundle exec jekyll build --source ./docs --destination ./docs/_site

